// A small rotating bank for the "question of the day" tile. The AI interviewer
// writes its own questions; these are common, role-agnostic openers.
export const DAILY_QUESTIONS = [
  'Tell me about yourself.',
  'Why do you want to work here?',
  'Describe a time you disagreed with a teammate. What happened?',
  'What is your biggest weakness, and what are you doing about it?',
  'Tell me about a project you are proud of. What was your part in it?',
  'Describe a time you failed. What did you learn?',
  'How do you prioritise when everything feels urgent?',
  'Tell me about a time you had to learn something quickly.',
  'Why are you leaving your current role?',
  'Where do you want to be in three years?',
  'Describe a time you led without formal authority.',
  'Tell me about a time you received difficult feedback.',
  'What would your last manager say about you?',
  'Walk me through a decision you made with incomplete information.',
  'How do you handle a deadline you know you will miss?',
  'Tell me about a time you helped a struggling colleague.',
  'What makes you the right person for this role?',
  'Describe a time you improved a process.',
  'How do you stay current in your field?',
  'Tell me about a conflict with a stakeholder and how you resolved it.',
  'What questions do you have for us?',
  'Describe your ideal working environment.',
  'Tell me about a time you had to persuade someone.',
  'What is the hardest problem you have solved recently?',
];
